pipeline{
    agent{
        node{
            label 'jenkins_agent_alpine'
        }
    }
    stages{
        stage('Build'){
            steps{
                echo "Building.."
                sh '''
                echo "doing build stuff.."
                '''
            }
        }
        stage('Test'){
            steps{
                echo "Testing"
                sh '''
                echo "Doing test stuff"
                '''
            }
        }
        stage('Deliver'){
            steps{
                echo "Deliver"
                sh '''
                echo "Doing delivery stuff"
                '''
            }
        }
    }
}
